// Copyright (c) 2025-2026 LIJIALU. MIT License.

//! Named-pipe server for the EasySearch IPC channel.
//!
//! # Windows
//!
//! Runs a synchronous accept loop on a dedicated thread per client.
//! Each client gets one pipe instance; after disconnect the instance is
//! recycled and a fresh `CreateNamedPipeW` is posted for the next client.
//!
//! Security: the pipe DACL is `D:(A;;GA;;;<user-sid>)` �?only the exact
//! Windows user who launched the daemon can connect. Generated by
//! [`uffs_security::pipe::OwnerOnlySd`].
//!
//! Pipe name: `\\.\pipe\easysearch-<fnv1a64(user-sid)>` �?deterministic per
//! user, computed by [`uffs_security::pipe::PipeName::for_current_user`].
//!
//! # Non-Windows
//!
//! Returns a placeholder pipe name only; the server function is a no-op
//! stub. The stdin/stdout loop in `main.rs` is used instead.

/// Return the named-pipe path for the current user.
///
/// On Windows this resolves the real user SID and hashes it.
/// On other platforms it returns a stable development placeholder.
#[must_use]
pub(crate) fn pipe_name_for_current_user() -> String {
    #[cfg(windows)]
    {
        uffs_security::pipe::PipeName::for_current_user()
            .map(|n| n.as_str().to_owned())
            .unwrap_or_else(|_| String::from(r"\\.\pipe\easysearch-fallback"))
    }
    #[cfg(not(windows))]
    {
        String::from(r"\\.\pipe\easysearch-current-user")
    }
}

// ── Windows named-pipe server ─────────────────────────────────────────────

#[cfg(windows)]
pub(crate) mod server {
    //! Synchronous multi-client named-pipe accept loop.

    use std::io::{BufRead as _, BufReader, Write as _};
    use std::sync::{Arc, Mutex};

    use windows::Win32::Foundation::{CloseHandle, HANDLE, INVALID_HANDLE_VALUE};
    use windows::Win32::Storage::FileSystem::{
        FILE_FLAG_FIRST_PIPE_INSTANCE, PIPE_ACCESS_DUPLEX,
    };
    use windows::Win32::System::Pipes::{
        ConnectNamedPipe, CreateNamedPipeW, DisconnectNamedPipe, PIPE_READMODE_BYTE,
        PIPE_TYPE_BYTE, PIPE_UNLIMITED_INSTANCES, PIPE_WAIT,
    };
    use windows::core::PCWSTR;

    use crate::service::EsService;

    const MAX_INSTANCES: u32 = PIPE_UNLIMITED_INSTANCES;
    const PIPE_BUFFER_SIZE: u32 = 65_536;
    const PIPE_DEFAULT_TIMEOUT_MS: u32 = 5_000;

    /// Run the named-pipe server. Blocks until [`EsService::should_shutdown`]
    /// returns `true` or an unrecoverable error occurs.
    pub(crate) fn run(
        service: Arc<Mutex<EsService>>,
        pipe_name: &str,
    ) -> Result<(), std::io::Error> {
        let pipe_name_wide: Vec<u16> =
            pipe_name.encode_utf16().chain(std::iter::once(0)).collect();

        let sd = uffs_security::pipe::OwnerOnlySd::for_current_user().map_err(|err| {
            std::io::Error::other(format!("failed to build pipe security descriptor: {err}"))
        })?;
        let mut sa = sd.as_security_attributes();

        let mut first_instance = true;

        loop {
            if service
                .lock()
                .map(|svc| svc.should_shutdown())
                .unwrap_or(true)
            {
                break;
            }

            let open_mode = if first_instance {
                PIPE_ACCESS_DUPLEX | FILE_FLAG_FIRST_PIPE_INSTANCE
            } else {
                PIPE_ACCESS_DUPLEX
            };

            #[expect(unsafe_code, reason = "CreateNamedPipeW Win32 FFI")]
            let handle = unsafe {
                CreateNamedPipeW(
                    PCWSTR(pipe_name_wide.as_ptr()),
                    open_mode,
                    PIPE_TYPE_BYTE | PIPE_READMODE_BYTE | PIPE_WAIT,
                    MAX_INSTANCES,
                    PIPE_BUFFER_SIZE,
                    PIPE_BUFFER_SIZE,
                    PIPE_DEFAULT_TIMEOUT_MS,
                    Some(std::ptr::from_mut(&mut sa)),
                )
            };

            if handle == INVALID_HANDLE_VALUE {
                return Err(std::io::Error::last_os_error());
            }

            first_instance = false;

            #[expect(unsafe_code, reason = "ConnectNamedPipe Win32 FFI")]
            let connect_result = unsafe { ConnectNamedPipe(handle, None) };

            if let Err(win_err) = connect_result {
                if win_err.code().0 != 535_i32 {
                    #[expect(unsafe_code, reason = "CloseHandle Win32 FFI")]
                    unsafe {
                        let _ = CloseHandle(handle);
                    }
                    continue;
                }
            }

            serve_client(Arc::clone(&service), handle);

            #[expect(unsafe_code, reason = "DisconnectNamedPipe Win32 FFI")]
            unsafe {
                let _ = DisconnectNamedPipe(handle);
            }
            #[expect(unsafe_code, reason = "CloseHandle Win32 FFI")]
            unsafe {
                let _ = CloseHandle(handle);
            }

            if service
                .lock()
                .map(|svc| svc.should_shutdown())
                .unwrap_or(true)
            {
                break;
            }
        }

        Ok(())
    }

    fn serve_client(service: Arc<Mutex<EsService>>, handle: HANDLE) {
        use crate::protocol::Response;

        let pipe_file = HandleFile(handle);
        let mut reader = BufReader::new(pipe_file);
        let mut writer = HandleFile(handle);

        let mut line = String::new();
        loop {
            line.clear();
            match reader.read_line(&mut line) {
                Ok(0) => break,
                Ok(_) => {}
                Err(_) => break,
            }

            let trimmed = line.trim();
            if trimmed.is_empty() {
                continue;
            }

            let response = match service.lock() {
                Ok(mut guard) => guard.handle_json_line(trimmed),
                Err(_) => Response::error(0, "service lock poisoned"),
            };

            if let Ok(json) = serde_json::to_vec(&response) {
                let _ = writer.write_all(&json);
                let _ = writer.write_all(b"\n");
                let _ = writer.flush();
            }

            let should_stop = match service.lock() {
                Ok(guard) => guard.should_shutdown(),
                Err(_) => true,
            };
            if should_stop {
                break;
            }
        }
    }

    struct HandleFile(HANDLE);

    impl std::io::Read for HandleFile {
        fn read(&mut self, buf: &mut [u8]) -> std::io::Result<usize> {
            use windows::Win32::Storage::FileSystem::ReadFile;
            let mut bytes_read = 0_u32;
            #[expect(unsafe_code, reason = "ReadFile Win32 FFI")]
            let result = unsafe {
                ReadFile(
                    self.0,
                    Some(buf),
                    Some(std::ptr::from_mut(&mut bytes_read)),
                    None,
                )
            };
            match result {
                Ok(()) => Ok(bytes_read as usize),
                Err(err) => {
                    let code = err.code().0;
                    if code == 109_i32 || code == 233_i32 {
                        Ok(0)
                    } else {
                        Err(std::io::Error::from_raw_os_error(code))
                    }
                }
            }
        }
    }

    impl std::io::Write for HandleFile {
        fn write(&mut self, buf: &[u8]) -> std::io::Result<usize> {
            use windows::Win32::Storage::FileSystem::WriteFile;
            let mut bytes_written = 0_u32;
            #[expect(unsafe_code, reason = "WriteFile Win32 FFI")]
            let result = unsafe {
                WriteFile(
                    self.0,
                    Some(buf),
                    Some(std::ptr::from_mut(&mut bytes_written)),
                    None,
                )
            };
            result.map_err(|err| std::io::Error::from_raw_os_error(err.code().0))?;
            Ok(bytes_written as usize)
        }

        fn flush(&mut self) -> std::io::Result<()> {
            use windows::Win32::Storage::FileSystem::FlushFileBuffers;
            #[expect(unsafe_code, reason = "FlushFileBuffers Win32 FFI")]
            unsafe { FlushFileBuffers(self.0) }
                .map_err(|err| std::io::Error::from_raw_os_error(err.code().0))
        }
    }
}
